### ISSUE TITLE
Api #5 out of 10

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/myhomemadeeasy.com#1]
@codextiny

new microsite: [https://myhomemadeeasy.com/](url)
Credentials:
U: [[support@homeowner.ai](mailto:support@homeowner.ai)]
PW: M!l3st0nesL@bs

1.Home Page: [https://myhomemadeeasy.com/](url)

Update search bar with API functionality

Add pop up form to Get Started Button in header on home page and Claim my home button on home page

How it Works [Page:](https://myhomemadeeasy.com/how-it-works/)
Add pop up form to claim my home button in hero image and cta at bottom

**Comment by codextiny** [comment]
@shannonbaldwin 

Done from our side, please check.

**Comment by shannonbaldwin** [comment]
@codextiny Please change the CTA button color the primary color (Red) on all pop-up forms.![image](https://github.com/user-attachments/assets/9c9acbe4-468c-4290-9b13-9d167bdaa538)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/5cad3b83-ee2b-424d-8e40-b2900e1cc655)

fixed, please check .
