### ISSUE TITLE
https://myhomemadeeasy.com/team/support-and-training/

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/myhomemadeeasy.com#2]
@codextiny 

Is there a way we can order the "All" section here? Also, I tried ordering the other sections (get started, homeowner experience, marketing) in WP but they are not ordering properly. 
![image](https://github.com/user-attachments/assets/291a38e6-a41f-44e8-af34-3ca22afab229)

![image](https://github.com/user-attachments/assets/52230485-ecae-48ed-afb3-235ccfbaa88f)Access:
[https://myhomemadeeasy.com/team/wp-admin/edit.php?post_type=portfolio](url)
support@milestones.ai
M!l3st0nesL@bs

**Comment by codextiny** [comment]
@shannonbaldwin 

We have tried to find out but there are no other options in WP and in your installed theme (your installed theme has a portfolio option but for the sidebar and select a page only). 

There is only one way to sort items right now, which is to use the default order field. We have tested it, and it's working but in descending order. So if you want to show an item first then that item should have the maximum number in the order field.

We have added some numbers for testing purposes (see screenshot) you can update them later.

![image](https://github.com/user-attachments/assets/af4a2eb5-f3d0-41ad-b481-35f345dd6a14)

![image](https://github.com/user-attachments/assets/7b1cf8ef-0bdc-4c96-b50c-cbffdc38af37)

![image](https://github.com/user-attachments/assets/fd8c94a3-5d55-4674-b6d0-23773852b244)

![image](https://github.com/user-attachments/assets/0b22e9e7-2f43-4d04-add1-c77813e8e198)

This sorting is also working fine on category single pages: https://myhomemadeeasy.com/team/support-and-training/?tax=portfolio_category&term=14#support-training

**Comment by shannonbaldwin** [comment]
@codextiny This worked. Thank you!

**Comment by shannonbaldwin** [comment]
@codextiny Can you please make this section of the testimonial mobile responsive (see image of headshot). 
[support@milestones.ai](mailto:support@milestones.ai)
M!l3st0nesL@bs

[https://myhomemadeeasy.com/wp-admin/post.php?post=180&action=elementor](url)

![image](https://github.com/user-attachments/assets/a0acb3c7-5080-460c-bcaf-4b76d65c9f81)

**Comment by codextiny** [comment]
@shannonbaldwin 

It's done please check
